# -*- coding: utf-8 -*-
"""Copy of Untitled5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1AFC_XnHwWUCzImUtMeYWh4ruQh-Wep-T
"""

List1=["what is your name","he is a boy","we love music"]

import string

isEven = lambda num : string.capwords(num)
newFilterdEvenList=map(isEven,List1)

list(newFilterdEvenList)