# -*- coding: utf-8 -*-
"""day:8 assignment no1 & 2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1DEaSoGuLl7H5Qn94Mhfh5nDLDOPa5g_o

#Aignment no 1 of DAY 8
"""

def fibonacci(num):
  def fibo(n):
    if n<=0:
      print("the number is incorrect")
    elif n==1:
      return 0
    elif n==2:
      return 1
    else :
       return(fibo(n-1)+fibo(n-2))
    return num(n)
  return fibo

@fibonacci
def fibo_num(n):
    print(n,"its the number")

fibo_num(1)

fibo_num(10)

fibo_num(20)

"""# Assignment 2 of Day 8"""

file =open("jupyter.txt","w")
file.write("hey whatsupp")
file.close()

file=open("jupyter.txt","r")
file.read()

file=open("jupyter.txt","a")
file.write("hey there")
file.close()

file=open("jupyter.txt")
file.close

file.close()